version: '3.4'

services:
  client:
    image: react-app-production
    restart: unless-stopped
    stdin_open: true
    ports:
      - 80:80
      - 443:443

  api-server:
    image: api-server-production
    restart: unless-stopped
    ports:
     - 3001:3001
    env_file: ./server/.env
