version: '3.4'

services:
  client:
    image: react-app
    build: ./client/
    stdin_open: true
    ports:
      - 3000:3000

  api-server:
    image: api-server
    build: ./server/
    ports:
     - 3001:3001
    env_file: ./server/.env
